# vim: set ft=ansible:
# export AWS_SECRET_ACCESS_KEY key
# export AWS_ACCESS_KEY_ID key_id

- hosts: localhost
  connection: local
  gather_facts: false
  vars:
      keypair: "{{ keypair }}"
      instance_type: "m4.large"
      image: "ami-9abea4fb"
      vpc_subnet_id: "{{ subnet_id }}"
      region: "us-west-2"
      availability_zone: "us-west-2c"
      price: 0.3
      db_volumes:
      - device_name: /dev/sda1
        volume_size: 64
        volume_type: gp2
        delete_on_termination: true

  roles:
    - { role: create_instance, instance: "generator", instance_volumes: []}
    - { role: create_instance, instance: "postgresql", instance_volumes: "{{ db_volumes }}", when: postgresql is defined}
    - { role: create_instance, instance: "mysql", instance_volumes: "{{ db_volumes }}", when: mysql is defined}
    - { role: create_instance, instance: "mongodb", instance_volumes: "{{ db_volumes }}", when: mongodb is defined}

  tasks:
    - shell: 'date +%Y%m%d%H%M%S%5N'
      register: timestamp

    - name: Wait for SSH to come up for all instances
      wait_for: host={{item}}
                port=22
                delay=60
                timeout=320
                state=started
      with_items: "{{ groups.ec2hosts }}"

- include: generator.yml
  vars:
    date: "{{ hostvars['localhost']['timestamp'].stdout }}"

- include: postgresql.yml
  when: postgresql is defined

- include: mysql.yml
  when: mysql is defined

- include: mongodb.yml
  when: mongodb is defined

- include: test_postgresql.yml
  when: postgresql is defined
  vars:
    date: "{{ hostvars['localhost']['timestamp'].stdout }}"

- include: test_mysql.yml
  when: mysql is defined
  vars:
    date: "{{ hostvars['localhost']['timestamp'].stdout }}"

- include: test_mongo.yml
  when: mongodb is defined
  vars:
    date: "{{ hostvars['localhost']['timestamp'].stdout }}"
