# vim: set ft=ansible:
- hosts: ec2generator
  gather_facts: false
  user: ubuntu
  vars:
    yscb_dir: /home/ubuntu/ycsb
  tasks:
    - name: install python 2
      raw: sudo bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qy python-minimal)"
      become: true

    - name: Update packages
      become: yes
      apt: update_cache=yes
           upgrade=dist

    - name: Install dependencies
      become: yes
      apt: name={{item}}
           state=installed
      with_items:
        - default-jdk
        - maven
        - git

    - name: Check ycsb archive
      local_action: stat path=ycsb.tar.lzma
      register: ycsb_archive

    - name: Clone yscb
      git: repo=https://github.com/erthalion/YCSB
           dest={{yscb_dir}}
           version=origin/jdbc-native-json-update
      when: not ycsb_archive.stat.exists

    - name: Copy ycsb
      copy: src=ycsb.tar.lzma dest=/home/ubuntu/
      when: ycsb_archive.stat.exists

    - name: Extract ycsb
      unarchive: src=ycsb.tar.lzma dest=./ copy=no
      when: ycsb_archive.stat.exists

    - name: Build ycsb
      command: chdir={{yscb_dir}} mvn -pl com.yahoo.ycsb:{{item.name}} -am  clean package
      with_items:
        - { name: mongodb-binding, skip: "{{mongodb is not defined}}" }
        - { name: pgjsonb-binding, skip: "{{postgresql is not defined}}" }
        - { name: mysqljson-binding, skip: "{{mysql is not defined}}" }
      when: not item.skip | bool

    - name: Set up options
      template:
        src=templates/options/{{ item.db }}.options.j2
        dest=/home/ubuntu/{{ item.db }}.options
      with_items:
        - { db: postgresql, skip: "{{postgresql is not defined}}" }
        - { db: mysql, skip: "{{ mysql is not defined }}" }
        - { db: mongo, skip: "{{ mongodb is not defined }}" }
      when: not item.skip | bool

    - name: Copy drivers
      copy:
        src=bindings
        dest=/home/ubuntu/ycsb/
