# vim: set ft=ansible:
- hosts: ec2hosts
  gather_facts: false
  user: ubuntu
  tasks:
    - name: install python 2
      raw: sudo bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qy python-minimal)"
      become: true

    - name: Create apt-daily directory
      become: yes
      file: path=/etc/systemd/system/apt-daily.timer.d state=directory

    - name: Disable unattended-upgrades
      become: yes
      action: template
        src=templates/confs/apt-daily.timer.conf
        dest=/etc/systemd/system/apt-daily.timer.d/apt-daily.timer.conf

    - pause:
        seconds: 5

    - name: Remove lock file
      become: yes
      file: path=/var/lib/dpkg/lock state=absent

    - name: Update packages
      become: yes
      apt: update_cache=yes
           upgrade=dist
      register: update_result
      until: update_result.stderr == ""
      retries: 10
      delay: 1
      ignore_errors: yes

    - name: Install dependencies
      become: yes
      apt: name={{item}}
           state=installed
      with_items:
        - sysstat

    - name: Configure sar
      template:
        src=templates/confs/sysstat.j2
        dest=/etc/default/sysstat
      become: true

    - name: Start sar
      shell: sar -o /home/ubuntu/sar_metrics 1 &

  handlers:
    - name: restart sysstat
      become: yes
      service:
        name=sysstat
        state=restarted
