# vim: set ft=ansible:
- hosts: ec2postgresql
  gather_facts: false
  user: ubuntu
  tasks:
    - include: install_postgres_deb.yml
      when: postgres_from_deb is defined

    - include: install_postgres_source.yml
      when: postgres_from_source is defined

    - name: Install pg_view dependencies
      become: yes
      apt: name={{item}}
           state=installed
      with_items:
        - python-psycopg2
        - python-pip

    - name: Install pg_view
      become: yes
      pip: name=pg_view

    - name: Template Postgresql configuration file
      become: yes
      action: template
        src=templates/confs/{{ item }}.conf.j2
        dest=/etc/postgresql/9.6/main/{{ item }}.conf
      with_items:
        - pg_hba
        - postgresql
      notify:
        - restart postgresql
      when: postgres_from_deb is defined

    - name: Template Postgresql configuration file
      become: yes
      become_user: postgres
      action: template
        src=templates/confs/{{ item.source }}.conf.j2
        dest=/home/postgres/build/data/{{ item.target }}.conf
      with_items:
        - { source: "pg_hba", target: "pg_hba"}
        - { source: "postgresql_from_source", target: "postgresql" }
      when: postgres_from_source is defined

    - name: restart postgresql
      become: yes
      become_user: postgres
      shell: ./bin/pg_ctl -D data restart chdir=/home/postgres/build/
      when: postgres_from_source is defined

    - meta: flush_handlers

    - name: Create user
      postgresql_user:
        name={{ db_user }}
        password={{ db_pass }}
        role_attr_flags=CREATEDB,SUPERUSER
        state=present
        encrypted=yes
      become: yes
      become_user: postgres
      become_method: sudo

    - name: Create user database
      postgresql_db:
        name={{ db_user }}
        login_user={{ db_user }}
        login_password={{ db_pass }}

    - name: Create YCSB database
      postgresql_db:
        name=ycsb
        login_user={{ db_user }}
        login_password={{ db_pass }}

    - name: Copy init sql
      template:
        src=templates/init/pg_init.sql
        dest=/home/postgres/pg_init.sql
      become: yes
      become_user: postgres

    - name: Create usertable with jsonb
      shell: psql -h /var/run/postgresql ycsb -U {{ db_user }} < /home/postgres/pg_init.sql
      become: yes
      become_user: postgres
      environment:
        PATH: $PATH:/home/postgres/build/bin

    - name: Start pg_view
      command: pg_view -o json > /home/ubuntu/postgresql.json &

  environment:
    PGPASSWORD: "{{ db_pass }}"

  handlers:
    - name: restart postgresql
      become: yes
      service:
        name=postgresql
        state=restarted
      when: postgres_from_deb is defined
