# vim: set ft=ansible:
- hosts: ec2generator
  gather_facts: false
  user: ubuntu
  vars:
    dest_directory: "./{{ workload }}_threads_{{ threads }}_{{ date }}"

  tasks:
    - include: test.yml
      vars:
        dest_directory: "./{{ workload }}_threads_{{ item }}_{{ date }}"
        db: mysql
        db_parameters: mysqljson -s -cp jdbc-binding/lib/mysql-connector-java-5.1.38-bin.jar
      with_items: "{{ thread_list }}"
      when: mysql8 is not defined

    - include: test.yml
      vars:
        dest_directory: "./{{ workload }}_threads_{{ item }}_{{ date }}"
        db: mysql
        db_parameters: mysqljson -s -cp jdbc-binding/lib/mysql-connector-java-8.0.8-dmr-bin.jar
      with_items: "{{ thread_list }}"
      when: mysql8 is defined

- hosts: ec2mysql
  gather_facts: false
  user: ubuntu
  tasks:
    - include: metrics.yml
      vars:
        dest_directory: "./{{ workload }}_threads_{{ threads }}_{{ date }}"
        db: mysql
