# vim: set ft=ansible:
- hosts: ec2generator
  gather_facts: false
  user: ubuntu
  tasks:
    - name: Load data
      shell: ./bin/ycsb load mongodb -s -P workloads/{{ workload }} -P /home/ubuntu/mongo.options -threads 20
            chdir=/home/ubuntu/ycsb/
      register: load_mongo
      when: prevent_load is not defined

    - name: Run workload
      shell: ./bin/ycsb run mongodb -s -P workloads/{{ workload }} -P /home/ubuntu/mongo.options -threads {{ threads }}
            chdir=/home/ubuntu/ycsb/
      register: run_mongo

    - name: Save load to file
      copy: content={{ load_mongo }} dest=/home/ubuntu/load_mongo

    - name: Save result to file
      copy: content={{ run_mongo }} dest=/home/ubuntu/run_mongo

    - name: Fetch results
      fetch: src={{ item }} dest=./{{ workload }}_threads_{{ threads }}_{{ date }} fail_on_missing=yes
      with_items:
        - load_mongo
        - run_mongo
