# vim: set ft=ansible:
- hosts: ec2generator
  gather_facts: false
  user: ubuntu
  vars:
    dest_directory: "./{{ workload }}_threads_{{ threads }}_{{ date }}"

  tasks:
    - name: Load data
      shell: ./bin/ycsb load mysqljson -s -cp bindings/lib/mysql-connector-java-5.1.38-bin.jar -P workloads/workloada -P /home/ubuntu/mysql.options -threads 2
            chdir=/home/ubuntu/ycsb/
      register: load_mysql
      when: prevent_load is not defined

    - name: Run workload
      shell: ./bin/ycsb run mysqljson -s -cp bindings/lib/mysql-connector-java-5.1.38-bin.jar -P workloads/{{ workload }} -P /home/ubuntu/mysql.options -threads {{ threads }}
            chdir=/home/ubuntu/ycsb/
      register: run_mysql

    - name: Save load to file
      copy: content={{ load_mysql }} dest=/home/ubuntu/load_mysql

    - name: Save result to file
      copy: content={{ run_mysql }} dest=/home/ubuntu/run_mysql

    - name: Fetch results
      fetch: src={{ item }} dest={{ dest_directory }} fail_on_missing=yes
      with_items:
        - load_mysql
        - run_mysql

    - name: Fetch options
      fetch: src=/home/ubuntu/mysql.options dest={{ dest_directory }} fail_on_missing=yes
