# vim: set ft=ansible:
- hosts: ec2generator
  gather_facts: false
  user: ubuntu
  vars:
    dest_directory: "./{{ workload }}_threads_{{ threads }}_{{ date }}"

  tasks:
    - include: test.yml
      vars:
        dest_directory: "./{{ workload }}_threads_{{ item }}_{{ date }}"
        db: mongo
        db_parameters: mongodb
      with_items: "{{ thread_list }}"
