# vim: set ft=ansible:
- hosts: ec2generator
  gather_facts: false
  user: ubuntu
  vars:
    pg_host: "{{ groups['ec2postgresql'][0] }}"
  tasks:
    - name: Load data
      shell: ./bin/ycsb load pgjsonb -s -cp bindings/lib/postgresql-9.4.1207.jar -P /home/ubuntu/postgresql.options -P workloads/workloada -threads 2
            chdir=/home/ubuntu/ycsb/
