# vim: set ft=ansible:
- hosts: ec2generator
  gather_facts: false
  user: ubuntu
  vars:
    pg_host: "{{ groups['ec2postgresql'][0] }}"
  tasks:
    - name: Load data
      shell: ./bin/ycsb load pgjsonb -s -cp bindings/lib/postgresql-9.4.1207.jar -P workloads/workloada -P /home/ubuntu/postgresql.options -threads 2
            chdir=/home/ubuntu/ycsb/
      register: load_postgresql

    - name: Save result to file
      copy: content="{{ load_postgresql }}" dest=/home/ubuntu/load_postgresql

    - name: Fetch results
      fetch: src=load_postgresql dest=./ fail_on_missing=yes
