# vim: set ft=ansible:
- hosts: ec2generator
  gather_facts: false
  user: ubuntu
  vars:
    mysql_host: "{{ groups['ec2mysql'][0] }}"
  tasks:
    - name: Load data
      shell: ./bin/ycsb load mysqljson -s -cp bindings/lib/mysql-connector-java-5.1.38-bin.jar -P /home/ubuntu/mysql.options -P workloads/workloada -threads 2
            chdir=/home/ubuntu/ycsb/
