# vim: set ft=ansible:
- hosts: ec2postgresql
  gather_facts: false
  user: ubuntu
  tasks:
    - name: Start sar for loading
      shell: sar -o /home/ubuntu/sar_metrics_load 1 &
      when: skip_load == false

    - name: Init data
      become: yes
      become_user: postgres
      shell: ./bin/pgbench -s {{ pgbench_scale }} -i chdir={{ pg_dir }}

    - name: Stop sar for loading
      shell: "killall sar -q || :"

    - name: Start sar for run
      shell: sar -o /home/ubuntu/sar_metrics_run 1 &
      when: skip_test == false

    - name: Test
      become: yes
      become_user: postgres
      shell: ./bin/pgbench -T {{ pgbench_time }} -c {{ pgbench_clients }} -j {{ pgbench_clients }} > ./run_postgresql  chdir={{ pg_dir }}

    - name: Stop sar for test
      shell: "killall sar -q || :"

    - name: Fetch results for PostgreSQL
      fetch: src={{ pg_dir }}/run_postgresql dest="./{{ workload }}_threads_{{ pgbench_clients }}_{{ date }}"

    - include: metrics.yml
      vars:
        dest_directory: "./{{ workload }}_threads_{{ pgbench_clients }}_{{ date }}"
        db: postgresql
